# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value
env:
  - name: TZ
    value: Asia/Shanghai
  - name: LANG
    value: zh_CN.UTF-8
  - name: LANGUAGE
    value: zh_CN:zh
  - name: SPRING_PROFILES_ACTIVE
    valueFrom:
      secretKeyRef:
        name: common-env
        key: env.profile
  - name: ENCRYPTOR_PASSWORD
    valueFrom:
      secretKeyRef:
        name: common-env
        key:  encryptor.password
  - name: ENCRYPTOR_ALGORITHM
    valueFrom:
      secretKeyRef:
        name: common-env
        key: encryptor.algorithm
  - name: CERT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: cascert
        key: password
  - name: NACOS_CONFIG_NAMESPACE
    valueFrom:
      secretKeyRef:
        name: common-env
        key: nacos.config.namespace
  - name: NACOS_CONFIG_SERVER_ADDR
    valueFrom:
      secretKeyRef:
        name: common-env
        key: nacos.config.server-addr

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: sale-service
  type: ClusterIP
  externalPort: 8017
  internalPort: 8017
  annotations:
    fabric8.io/expose: "false"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    memory: 1Gi
  requests:
    memory: 1Gi
probePath: /sale/actuator/health
livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
readinessProbe:
  initialDelaySeconds: 120
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
